"""added last seen column to db

Revision ID: 15746cb6d070
Revises: 2105194adf34
Create Date: 2022-07-26 12:55:07.599412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15746cb6d070'
down_revision = '2105194adf34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###
