"""added password field again

Revision ID: 5e83bc7f1026
Revises: 6d06c69e58fb
Create Date: 2022-07-22 21:54:26.593528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e83bc7f1026'
down_revision = '6d06c69e58fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password1', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password1')
    # ### end Alembic commands ###
