"""added password field

Revision ID: 6d06c69e58fb
Revises: 02b48aecadb0
Create Date: 2022-07-21 10:23:09.982942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d06c69e58fb'
down_revision = '02b48aecadb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
