"""added a new about author col to User Model

Revision ID: a361ffde8cb6
Revises: 02a2d52c4aee
Create Date: 2022-07-24 19:31:26.855483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a361ffde8cb6'
down_revision = '02a2d52c4aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'posts', 'users', ['blogger_id'], ['id'])
    op.drop_column('posts', 'poster_id')
    op.drop_column('posts', 'author')
    op.add_column('users', sa.Column('about_author', sa.Text(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_author')
    op.add_column('posts', sa.Column('author', sa.VARCHAR(length=255), nullable=True))
    op.add_column('posts', sa.Column('poster_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    # ### end Alembic commands ###
